
  create table "public"."api_keys" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "key" uuid default gen_random_uuid(),
    "user_id" uuid not null
      );


alter table "public"."api_keys" enable row level security;

CREATE UNIQUE INDEX api_keys_pkey ON public.api_keys USING btree (id);

alter table "public"."api_keys" add constraint "api_keys_pkey" PRIMARY KEY using index "api_keys_pkey";

alter table "public"."api_keys" add constraint "api_keys_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."api_keys" validate constraint "api_keys_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_user_id_from_api_key(api_key uuid)
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$DECLARE
  user_id uuid;
BEGIN
  select api_keys.user_id into user_id from api_keys where api_key = api_keys.key;
  return user_id;
END;$function$
;

grant delete on table "public"."api_keys" to "anon";

grant insert on table "public"."api_keys" to "anon";

grant references on table "public"."api_keys" to "anon";

grant select on table "public"."api_keys" to "anon";

grant trigger on table "public"."api_keys" to "anon";

grant truncate on table "public"."api_keys" to "anon";

grant update on table "public"."api_keys" to "anon";

grant delete on table "public"."api_keys" to "authenticated";

grant insert on table "public"."api_keys" to "authenticated";

grant references on table "public"."api_keys" to "authenticated";

grant select on table "public"."api_keys" to "authenticated";

grant trigger on table "public"."api_keys" to "authenticated";

grant truncate on table "public"."api_keys" to "authenticated";

grant update on table "public"."api_keys" to "authenticated";

grant delete on table "public"."api_keys" to "service_role";

grant insert on table "public"."api_keys" to "service_role";

grant references on table "public"."api_keys" to "service_role";

grant select on table "public"."api_keys" to "service_role";

grant trigger on table "public"."api_keys" to "service_role";

grant truncate on table "public"."api_keys" to "service_role";

grant update on table "public"."api_keys" to "service_role";


  create policy "Enable insert for users based on user_id"
  on "public"."api_keys"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable selects for users based on user_id"
  on "public"."api_keys"
  as permissive
  for select
  to public
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "API Key Upload 1nngobv_0"
  on "storage"."objects"
  as permissive
  for insert
  to service_role
with check ((bucket_id = 'sect_logs'::text));



  create policy "Add New Logs 1nngobv_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'sect_logs'::text));



  create policy "Allow All Read 1nngobv_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'sect_logs'::text));



