use crate::bt::*;
use behavior_bark::unpowered::*;
use serde::*;

use crate::{
    classes::group::*, observables::*, targetted_action, timeline::*, types::*, untargetted_action,
};

targetted_action!(Spark, "cast spark {}");
targetted_action!(AshenFeet, "cast ashenfeet {}");
untargetted_action!(FireburstCast, "cast fireburst");
targetted_action!(Fireburst, "fireburst {}");
targetted_action!(Blazewhirl, "cast blazewhirl {}");
targetted_action!(Conflagrate, "cast conflagrate {}");
untargetted_action!(Afterburn, "cast afterburn");
targetted_action!(Sunspot, "cast sunspot {}");
targetted_action!(Pyroclast, "cast pyroclast {}");
targetted_action!(Disintegrate, "cast disintegrate {}");
untargetted_action!(Coldsnap, "cast coldsnap");
targetted_action!(Drench, "cast drench {}");
targetted_action!(Iceray, "cast iceray {}");
targetted_action!(Glazeflow, "cast glazeflow {}");
targetted_action!(Direfrost, "cast direfrost {}");
targetted_action!(Icicle, "cast icicle {}");
untargetted_action!(Shatter, "cast shatter");
targetted_action!(Crystalise, "cast crystalise {}");
untargetted_action!(Winterheart, "cast winterheart");
targetted_action!(Windlance, "cast windlance {}");
targetted_action!(Pressurize, "cast pressurize {}");
targetted_action!(Arcbolt, "cast arcbolt {}");
targetted_action!(Electrosphere, "cast electrosphere {}");
targetted_action!(Thunderclap, "cast thunderclap {}");
targetted_action!(Feedback, "cast feedback {}");
targetted_action!(AeroblastFast, "cast aeroblast {} fast");
targetted_action!(AeroblastSlow, "cast aeroblast {} slow");
untargetted_action!(Stormwrath, "cast stormwrath");
untargetted_action!(Capacitance, "cast capacitance");

untargetted_action!(Fulcrum, "fulcrum construct");
untargetted_action!(FulcrumExpand, "fulcrum expand");
untargetted_action!(FulcrumCallback, "fulcrum callback");
untargetted_action!(FulcrumInterfuse, "fulcrum interfuse");
untargetted_action!(FulcrumPush, "fulcrum push");
untargetted_action!(Schism, "fulcrum schism on");
untargetted_action!(Imbalance, "fulcrum imbalance on");
untargetted_action!(FulcrumRestore, "fulcrum restore");
untargetted_action!(EnrichFire, "fulcrum enrich fire");
untargetted_action!(EnrichWater, "fulcrum enrich water");
untargetted_action!(EnrichAir, "fulcrum enrich air");
targetted_action!(Emberbrand, "fulcrum branding {} ember");
targetted_action!(Frostbrand, "fulcrum branding {} frost");
targetted_action!(Thunderbrand, "fulcrum branding {} thunder");
targetted_action!(CatalystEmber, "fulcrum catalyst {} ember");
targetted_action!(CatalystFrost, "fulcrum catalyst {} frost");
targetted_action!(CatalystThunder, "fulcrum catalyst {} thunder");
targetted_action!(Enrapture, "fulcrum enrapture {}");
targetted_action!(FulcrumDetect, "fulcrum detect {}");
untargetted_action!(Shift, "fulcrum shift");
untargetted_action!(Degradation, "fulcrum degradation on");
untargetted_action!(Spiritrift, "fulcrum spiritrift on");
