type LearnerScenario = {
  attacker: string;
  target: string;
  horizon_ms: number;
  candidate_actions: string[];
};

type LearnerResult = {
  best_action_order: string[];
  score: number;
  expected_observations: number;
  used_timeline: boolean;
  used_observables: boolean;
  notes: string[];
};

let initialized = false;

async function loadWasm() {
  // This file is generated by wasm-pack.
  // @ts-ignore - generated at build time.
  const wasmModule = await import('../src-wasm/pkg/topper_aetolia_learner_wasm.js');
  if (!initialized) {
    await wasmModule.default();
    initialized = true;
  }
  return wasmModule;
}

export async function runLearnerSimulation(
  scenario: LearnerScenario
): Promise<LearnerResult> {
  const wasm = await loadWasm();
  const raw = wasm.simulate_plan(JSON.stringify(scenario));
  return raw as LearnerResult;
}
