<script lang="ts">
	import PublishLog from "$lib/PublishLog.svelte";
	import Readme from "$lib/Readme.svelte";

	let { data } = $props();
	let { user } = $derived(data);
	let logged_in = $derived(user !== null);
</script>

<svelte:head>
	<title>Sect Watch - Home</title>
</svelte:head>

<Readme title="Seurimas' Sect Watch">
	<p>
		<span class="sect_watch">Sect Watch</span> is a tool for sharing, viewing, and commenting on logs for the online roleplaying MUD,
		<a href="http://aetolia.com">Aetolia</a>. 
	</p>

	<p>
		You can find the source code for this project on
		<a href="http://github.com/seurimas/topper_public">GitHub</a>.
	</p>

	<h2>Viewing and Sharing Logs</h2>

	<p>
		To get started viewing logs, head to the <a href="/logs">Public Logs</a> page. There, you can browse logs that have been shared by other users.
	</p>

	<p>
		You can also publish your own logs to share them with the community. To do so, you'll need to link your Discord account by signing in via the <a href="/signin">Sign In</a> page.
		After signing in, you can upload logs using the upload form available on the main page. Rather than downloading and re-uploading log files manually, logs are shared through by the URL provided when reading your Sect logbook.
	</p>

	<PublishLog {logged_in} />

	<p>
		Sect Watch ONLY supports logs generated by the Sect logbook feature in Aetolia. If you are looking for a more general log sharing tool, consider using <a href="https://ada-young.com/pastebin/">Ada's HTML Pastebin</a>.
	</p>

	<h2>API Information</h2>

	<p>
		You may also upload logs directly to the Sect Watch API from your MUD client. Documentation for the API can be found on the <a href="/api">API Info</a> page.
	</p>

	<h2>Notice</h2>

	<p>
		Sect Watch is not affiliated with Aetolia or Iron Realms Entertainment in any way. It is a third-party tool created by the community for the community.
	</p>
</Readme>

<style>
	@reference "tailwindcss";

	h2 {
		@apply text-2xl font-bold mt-6 mb-2;
	}

	p {
		@apply mb-4;
	}

	.sect_watch {
		@apply font-bold text-amber-200;
	}

	a {
		@apply text-blue-500 underline hover:text-blue-700;
	}
</style>